# Gitpod configuration for Rocket.Chat development.
# See https://developer.rocket.chat/open-source-projects/server/server-environment-setup/gitpod

# Please adjust to your needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

# More on tasks: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks: 
  - name: dev-server # terminal name
    # More on environment variables: https://www.gitpod.io/docs/configure/projects/environment-variables
    env:
      # https://github.com/RocketChat/Rocket.Chat/blob/8da72776017a971bb02d27a6e1d602ec975eaf03/server/startup/initialData.coffee#L28
      # https://github.com/RocketChat/feature-requests/issues/778#issuecomment-1490827711
      ADMIN_USERNAME: admin
      ADMIN_PASS: admin
      ADMIN_EMAIL: admin@example.com
      OVERWRITE_SETTING_Show_Setup_Wizard: completed
    # before: Use this for tasks that need to run before init and before command. For example, customize the terminal
    # or install global project dependencies.
    #
    # To run multiple commands for a given task, you can use the | notation where each line below (make sure you indent 
    # correctly) runs in sequence once the previous command terminates.
    #
    # - switch to node.js ver 14.21.3
    # - install Meteor. Read required version form https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/apps/meteor/.meteor/release
    # - create ROOT_URL variable - optional task
    before: |
      nvm install 14.21.3 &&
      curl https://install.meteor.com/?release=$( curl -so- https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/apps/meteor/.meteor/release | cut -d@ -f2) | sh &&
      meteor --version &&
      export ROOT_URL=$(gp url 3000)
    # init: Use this for heavy-lifting tasks such as downloading dependencies or compiling source code.
    init: |
      yarn install &&
      yarn run build
    # command: Use this to start your database or development server.
    command: |
      yarn run dev

